# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/err.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(336, 189)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.err_msg = QtWidgets.QLabel(Dialog)
        self.err_msg.setGeometry(QtCore.QRect(0, 24, 336, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.err_msg.setFont(font)
        self.err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.err_msg.setWordWrap(True)
        self.err_msg.setObjectName("err_msg")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(118, 130, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ТехноМир - Ошибка"))
        self.err_msg.setText(_translate("Dialog", "Неверный логин и\\или пароль!\n"
"Попробуйте еще раз!"))
        self.ok_btn.setText(_translate("Dialog", "Ок"))
