# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 288)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setGeometry(QtCore.QRect(240, 80, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_edit.setFont(font)
        self.login_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_edit.setClearButtonEnabled(True)
        self.login_edit.setObjectName("login_edit")
        self.pswd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.pswd_edit.setGeometry(QtCore.QRect(240, 130, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pswd_edit.setFont(font)
        self.pswd_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswd_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pswd_edit.setClearButtonEnabled(True)
        self.pswd_edit.setObjectName("pswd_edit")
        self.login_lbl = QtWidgets.QLabel(self.centralwidget)
        self.login_lbl.setGeometry(QtCore.QRect(130, 85, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_lbl.setFont(font)
        self.login_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.login_lbl.setObjectName("login_lbl")
        self.pswd_lbl = QtWidgets.QLabel(self.centralwidget)
        self.pswd_lbl.setGeometry(QtCore.QRect(140, 130, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pswd_lbl.setFont(font)
        self.pswd_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pswd_lbl.setObjectName("pswd_lbl")
        self.entry_btn = QtWidgets.QPushButton(self.centralwidget)
        self.entry_btn.setGeometry(QtCore.QRect(201, 180, 110, 32))
        self.entry_btn.setObjectName("entry_btn")
        self.entry_lbl = QtWidgets.QLabel(self.centralwidget)
        self.entry_lbl.setGeometry(QtCore.QRect(180, 30, 170, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_lbl.sizePolicy().hasHeightForWidth())
        self.entry_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entry_lbl.setFont(font)
        self.entry_lbl.setWordWrap(False)
        self.entry_lbl.setObjectName("entry_lbl")
        self.entry_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.entry_lbl_2.setGeometry(QtCore.QRect(140, 220, 261, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_lbl_2.sizePolicy().hasHeightForWidth())
        self.entry_lbl_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entry_lbl_2.setFont(font)
        self.entry_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.entry_lbl_2.setWordWrap(False)
        self.entry_lbl_2.setObjectName("entry_lbl_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ТехноМир - Авторизация"))
        self.login_lbl.setText(_translate("MainWindow", "Логин"))
        self.pswd_lbl.setText(_translate("MainWindow", "Пароль"))
        self.entry_btn.setText(_translate("MainWindow", "Войти"))
        self.entry_lbl.setText(_translate("MainWindow", "Войдите в систему"))
        self.entry_lbl_2.setText(_translate("MainWindow", "Оставьте поля ввода логина и пароля\n"
" пустыми для входа в качестве покупателя!"))
