--1

SELECT DISTINCT M.NAME, M.HORSEPOWER, MF.YEAR
FROM MODEL M
JOIN MODEL_TO_FACTORY MF ON M.ID = MF.MODEL_ID
WHERE MF.YEAR < 1970 AND M.HORSEPOWER > 200;

--2

SELECT DISTINCT M.NAME, MF.YEAR
FROM MODEL M
JOIN MODEL_TO_FACTORY MF ON M.ID = MF.MODEL_ID
WHERE MF.YEAR BETWEEN 1995 AND 2000;

--3

SELECT NAME, FOUNDER
FROM BRAND
WHERE FOUNDER LIKE 'H%';

--4

SELECT NAME, ENGINE_CAPACITY
FROM MODEL
WHERE BRAND_ID in
		(SELECT ID
		FROM BRAND
		WHERE COUNTRY = 'Italy');

--5

SELECT OPEN_YEAR
FROM FACTORY AS JT_FAC
WHERE CITY = 'Johntown'
	AND EXISTS
		(SELECT OPEN_YEAR
			FROM FACTORY
			WHERE CITY = 'Turnerville'
				AND OPEN_YEAR = JT_FAC.OPEN_YEAR);

--6

SELECT ID, NAME, PRODUCT_VOLUME, OPEN_YEAR
FROM FACTORY
WHERE PRODUCT_VOLUME > ALL
		(SELECT PRODUCT_VOLUME
		FROM FACTORY
		WHERE OPEN_YEAR > 2000);

--7

SELECT B.NAME, B.COUNTRY,
	SUM(PRODUCT_VOLUME),
	AVG(PRODUCT_VOLUME),
	COUNT(*)
FROM FACTORY F
JOIN BRAND B ON F.BRAND_ID = B.ID
GROUP BY B.ID;

--8

SELECT NAME, COUNTRY,
	(SELECT AVG(ENGINE_CAPACITY)
		FROM MODEL
		WHERE MODEL.BRAND_ID = BRAND.ID) AS AVGCAP,
	(SELECT MIN(HORSEPOWER)
		FROM MODEL
		WHERE MODEL.BRAND_ID = BRAND.ID) AS MINPOW,
	FOUND_YEAR
FROM BRAND
WHERE FOUND_YEAR < 1980;

--9

SELECT COUNTRY, COUNT(*),
	CASE COUNT(*)
			WHEN (SELECT MAX(CNT)
				 FROM (SELECT COUNT(*) AS CNT
				 	   FROM BRAND
					   GROUP BY COUNTRY)T) THEN 'Max'
			WHEN 1 THEN 'Single'
			ELSE 'Few'
	END BRAND_QNT
FROM BRAND
GROUP BY COUNTRY;

--10

SELECT NAME, COUNTRY, FOUNDER,
	CASE
		WHEN FOUND_YEAR > 2000 THEN '21st'
		WHEN FOUND_YEAR > 1900 THEN '20th'
		ELSE '19th'
	END AS FOUND_CENT
FROM BRAND;

--11

SELECT COUNTRY, COUNT(*) AS CNT INTO TEMP MULTBRANDS
FROM BRAND
GROUP BY COUNTRY
HAVING COUNT(*) > 1
ORDER BY CNT DESC;


SELECT *
FROM MULTBRANDS;

--12

SELECT *
FROM BRAND B, LATERAL(SELECT MIN(FOUND_YEAR) as MinByCountry
			FROM BRAND
			WHERE COUNTRY = B.COUNTRY) FB;

--13

SELECT *
FROM BRAND WHERE COUNTRY =
	(SELECT COUNTRY
	FROM BRAND
	GROUP BY COUNTRY
	HAVING COUNT(*) =
			(SELECT MAX(CNT)
			 FROM
			(SELECT COUNT(*) AS CNT
			 FROM BRAND
			 GROUP BY COUNTRY)T));

--14

SELECT F.NAME, F.CITY, COUNT(*) AS CNT
FROM MODEL M
JOIN MODEL_TO_FACTORY MF ON M.ID = MF.MODEL_ID
JOIN FACTORY F ON MF.FACTORY_ID = F.ID
GROUP BY F.NAME, F.CITY;

--15

SELECT YEAR, COUNT(*) AS QUANTITY
FROM MODEL M
JOIN MODEL_TO_FACTORY MF ON M.ID = MF.MODEL_ID
GROUP BY YEAR
HAVING COUNT(*) > 10
ORDER BY COUNT(*) DESC;

--16

INSERT INTO MODEL(BRAND_ID, NAME, ENGINE_CAPACITY, HORSEPOWER)
VALUES (1, 'Logan', 1.6, 102);

--17

INSERT INTO MODEL(BRAND_ID, NAME, ENGINE_CAPACITY, HORSEPOWER)
SELECT MIN(ID), 'Qashqai', 2.0, 144
FROM BRAND
WHERE NAME = 'Nissan';


SELECT *
FROM MODEL
WHERE ID > 1000;

--18

SELECT *
FROM MODEL
WHERE ID = 3;


UPDATE MODEL
SET ENGINE_CAPACITY = ENGINE_CAPACITY * 0.9
WHERE ID = 3;

--19

UPDATE MODEL
SET ENGINE_CAPACITY =
		(SELECT AVG(ENGINE_CAPACITY)
		FROM MODEL
		WHERE BRAND_ID = 15)
WHERE BRAND_ID = 16;


SELECT *
FROM MODEL
WHERE BRAND_ID = 16;

--20

DELETE
FROM MODEL
WHERE ID > 1000;


SELECT *
FROM MODEL
WHERE ID > 1000;

--21

DELETE
FROM BRAND B
WHERE FOUND_YEAR = (SELECT MIN(FOUND_YEAR)
			FROM BRAND
			WHERE COUNTRY = B.COUNTRY);

--22
 WITH FIRSTBRANDS(COUNTRY, QTY) AS
(SELECT COUNTRY, COUNT(NAME)
 FROM BRAND
 GROUP BY COUNTRY)
SELECT COUNTRY, QTY
FROM FIRSTBRANDS
WHERE QTY = (SELECT MAX(QTY) FROM FIRSTBRANDS);

--23
WITH RECURSIVE BRANDLEVEL (ID, FOUND_YEAR, LEVEL) AS
	(SELECT B.ID, B.FOUND_YEAR, 0
	 FROM BRAND AS B
	 WHERE B.FOUND_YEAR = 1870
	 UNION 
	 SELECT BR.ID, BR.FOUND_YEAR, LEVEL + 1
	 FROM BRAND AS BR JOIN BRANDLEVEL AS BL ON BR.FOUND_YEAR = BL.FOUND_YEAR + 1)
SELECT *
FROM BRANDLEVEL;

--24

SELECT DISTINCT B.NAME, B.COUNTRY,
	MIN(ENGINE_CAPACITY) OVER (PARTITION BY B.NAME, B.COUNTRY) AS MINCAP,
	MAX(ENGINE_CAPACITY) OVER (PARTITION BY B.NAME, B.COUNTRY) AS MAXCAP,
	AVG(ENGINE_CAPACITY) OVER (PARTITION BY B.NAME, B.COUNTRY) AS AVGCAP
FROM MODEL M
JOIN BRAND B ON M.BRAND_ID = B.ID;

--25
WITH DUPLICATES(NAME, COUNTRY, MINCAP, N) AS
	(SELECT B.NAME, B.COUNTRY,
		MIN(ENGINE_CAPACITY) OVER (PARTITION BY B.NAME, B.COUNTRY), 
	 	ROW_NUMBER() OVER (PARTITION BY B.NAME, B.COUNTRY)
	FROM MODEL M JOIN BRAND B ON M.BRAND_ID = B.ID)
SELECT *
FROM DUPLICATES
WHERE N = 1;



--def

SELECT m.name, b.name
from model m join brand b on m.brand_id = b.id
where country = 'Bangladesh';

select country, count(*)
from brand
group by country;